#!/usr/bin/env python3
"""Extract the official Tibia application's embedded Qt/QML resources.

The macOS client links one or more resource trees generated by Qt's ``rcc``.
Those trees are registered through calls shaped like::

    qRegisterResourceData(3, resource_tree, resource_names, resource_payloads)

This tool finds those calls in an x86_64 Mach-O executable, decodes the Qt
resource format, selects the tree containing the Tibia application QML, and
writes the decoded files with their original virtual paths.

It intentionally does not modify the official application bundle.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import struct
import sys
import zlib
from dataclasses import dataclass
from pathlib import Path, PurePosixPath


DEFAULT_CLIENT = (
    Path.home()
    / "Library/Application Support/CipSoft GmbH/Tibia/packages/Tibia.app/Contents/MacOS/client"
)
DEFAULT_OUTPUT = Path("data/official-client-15.3x/qml-resources")
DEFAULT_MANIFEST = Path("data/official-client-15.3x/qml-resources-manifest.json")

MACHO_MAGIC_64 = 0xFEEDFACF
LC_SEGMENT_64 = 0x19
QT_RESOURCE_ENTRY_SIZE_V2 = 22
QT_RESOURCE_COMPRESSED_ZLIB = 0x01
QT_RESOURCE_DIRECTORY = 0x02
QT_RESOURCE_COMPRESSED_ZSTD = 0x04

# lea rel32(%rip), %rsi; lea rel32(%rip), %rdx; lea rel32(%rip), %rcx;
# mov $3, %edi; call rel32. Both registration and cleanup functions use the
# same setup, so decoded pointer triples are de-duplicated below.
REGISTER_PATTERN = re.compile(
    rb"\x48\x8d\x35(?P<rsi>.{4})"
    rb"\x48\x8d\x15(?P<rdx>.{4})"
    rb"\x48\x8d\x0d(?P<rcx>.{4})"
    rb"\xbf\x03\x00\x00\x00\xe8.{4}",
    re.DOTALL,
)


class ExtractionError(RuntimeError):
    """Raised for a malformed or unsupported executable/resource tree."""


@dataclass(frozen=True)
class Segment:
    name: str
    vm_address: int
    vm_size: int
    file_offset: int
    file_size: int


@dataclass(frozen=True)
class Registration:
    call_site_offset: int
    tree_offset: int
    names_offset: int
    payloads_offset: int


@dataclass(frozen=True)
class Resource:
    path: str
    flags: int
    territory: int
    language: int
    modified_msec: int
    data_offset: int


class MachOImage:
    def __init__(self, path: Path) -> None:
        self.path = path
        try:
            self.data = path.read_bytes()
        except OSError as error:
            raise ExtractionError(f"cannot read executable {path}: {error}") from error
        self.segments = self._parse_segments()

    def _parse_segments(self) -> list[Segment]:
        if len(self.data) < 32:
            raise ExtractionError("file is too small to be a Mach-O executable")
        magic = struct.unpack_from("<I", self.data, 0)[0]
        if magic != MACHO_MAGIC_64:
            raise ExtractionError(
                "expected a little-endian 64-bit Mach-O executable; "
                f"found magic 0x{magic:08x}"
            )

        command_count = struct.unpack_from("<I", self.data, 16)[0]
        command_offset = 32
        segments: list[Segment] = []
        for _ in range(command_count):
            if command_offset + 8 > len(self.data):
                raise ExtractionError("truncated Mach-O load-command table")
            command, command_size = struct.unpack_from("<II", self.data, command_offset)
            if command_size < 8 or command_offset + command_size > len(self.data):
                raise ExtractionError("invalid Mach-O load-command size")
            if command == LC_SEGMENT_64:
                if command_size < 72:
                    raise ExtractionError("truncated LC_SEGMENT_64 command")
                raw_name = self.data[command_offset + 8 : command_offset + 24]
                name = raw_name.split(b"\0", 1)[0].decode("ascii", "replace")
                vm_address, vm_size, file_offset, file_size = struct.unpack_from(
                    "<QQQQ", self.data, command_offset + 24
                )
                segments.append(
                    Segment(name, vm_address, vm_size, file_offset, file_size)
                )
            command_offset += command_size
        if not segments:
            raise ExtractionError("Mach-O executable has no 64-bit segments")
        return segments

    def file_to_vm(self, file_offset: int) -> int:
        for segment in self.segments:
            if segment.file_offset <= file_offset < segment.file_offset + segment.file_size:
                return segment.vm_address + file_offset - segment.file_offset
        raise ExtractionError(f"file offset 0x{file_offset:x} is outside mapped segments")

    def vm_to_file(self, vm_address: int) -> int:
        for segment in self.segments:
            if segment.vm_address <= vm_address < segment.vm_address + segment.file_size:
                return segment.file_offset + vm_address - segment.vm_address
        raise ExtractionError(f"VM address 0x{vm_address:x} is outside file-backed segments")

    def registrations(self) -> list[Registration]:
        registrations: dict[tuple[int, int, int], Registration] = {}
        for match in REGISTER_PATTERN.finditer(self.data):
            call_site = match.start()
            instruction_vm = self.file_to_vm(call_site)
            target_vms = []
            for index, group_name in enumerate(("rsi", "rdx", "rcx")):
                displacement = struct.unpack("<i", match.group(group_name))[0]
                next_instruction_vm = instruction_vm + (index + 1) * 7
                target_vms.append(next_instruction_vm + displacement)
            try:
                offsets = tuple(self.vm_to_file(address) for address in target_vms)
            except ExtractionError:
                continue
            registration = Registration(call_site, offsets[0], offsets[1], offsets[2])
            registrations.setdefault(offsets, registration)
        return sorted(registrations.values(), key=lambda item: item.tree_offset)


class QtResourceTree:
    def __init__(self, image: MachOImage, registration: Registration) -> None:
        self.image = image
        self.registration = registration
        self._entry_limit = max(
            0,
            (registration.names_offset - registration.tree_offset)
            // QT_RESOURCE_ENTRY_SIZE_V2,
        )

    def _entry_offset(self, node: int) -> int:
        if not 0 <= node < self._entry_limit:
            raise ExtractionError(f"resource node {node} is outside the tree")
        return self.registration.tree_offset + node * QT_RESOURCE_ENTRY_SIZE_V2

    def _name(self, node: int) -> str:
        if node == 0:
            return ""
        entry_offset = self._entry_offset(node)
        relative_offset = struct.unpack_from(">I", self.image.data, entry_offset)[0]
        name_offset = self.registration.names_offset + relative_offset
        if name_offset + 6 > self.registration.payloads_offset:
            raise ExtractionError(f"resource node {node} has an invalid name offset")
        length = struct.unpack_from(">H", self.image.data, name_offset)[0]
        encoded_offset = name_offset + 6  # skip length and Qt name hash
        encoded_end = encoded_offset + length * 2
        if encoded_end > self.registration.payloads_offset:
            raise ExtractionError(f"resource node {node} has a truncated name")
        return self.image.data[encoded_offset:encoded_end].decode("utf-16-be")

    def _walk(self, node: int, parent: PurePosixPath, seen: set[int]) -> list[Resource]:
        if node in seen:
            raise ExtractionError(f"cycle detected at resource node {node}")
        seen.add(node)
        offset = self._entry_offset(node)
        flags = struct.unpack_from(">H", self.image.data, offset + 4)[0]
        name = self._name(node)
        path = parent / name if name else parent
        modified_msec = struct.unpack_from(">Q", self.image.data, offset + 14)[0]

        if flags & QT_RESOURCE_DIRECTORY:
            child_count, first_child = struct.unpack_from(">II", self.image.data, offset + 6)
            if child_count > self._entry_limit or first_child + child_count > self._entry_limit:
                raise ExtractionError(f"resource node {node} has an invalid child range")
            resources: list[Resource] = []
            for child in range(first_child, first_child + child_count):
                resources.extend(self._walk(child, path, seen))
            return resources

        territory, language, data_offset = struct.unpack_from(">HHI", self.image.data, offset + 6)
        resource_path = "/" + str(path).lstrip("/")
        return [
            Resource(
                resource_path,
                flags,
                territory,
                language,
                modified_msec,
                data_offset,
            )
        ]

    def resources(self) -> list[Resource]:
        if self._entry_limit == 0:
            raise ExtractionError("empty resource tree")
        root_offset = self._entry_offset(0)
        root_flags = struct.unpack_from(">H", self.image.data, root_offset + 4)[0]
        if not root_flags & QT_RESOURCE_DIRECTORY:
            raise ExtractionError("resource root is not a directory")
        return sorted(self._walk(0, PurePosixPath("/"), set()), key=lambda item: item.path)

    def decoded_payload(self, resource: Resource) -> tuple[bytes, str, int]:
        payload_offset = self.registration.payloads_offset + resource.data_offset
        if payload_offset + 4 > len(self.image.data):
            raise ExtractionError(f"{resource.path}: payload offset is outside the executable")
        stored_size = struct.unpack_from(">I", self.image.data, payload_offset)[0]
        stored_start = payload_offset + 4
        stored_end = stored_start + stored_size
        if stored_end > len(self.image.data):
            raise ExtractionError(f"{resource.path}: truncated payload")
        payload = self.image.data[stored_start:stored_end]

        compression_flags = resource.flags & (
            QT_RESOURCE_COMPRESSED_ZLIB | QT_RESOURCE_COMPRESSED_ZSTD
        )
        if compression_flags == 0:
            return payload, "none", stored_size
        if compression_flags == QT_RESOURCE_COMPRESSED_ZLIB:
            if len(payload) < 4:
                raise ExtractionError(f"{resource.path}: truncated qCompress payload")
            expected_size = struct.unpack_from(">I", payload, 0)[0]
            try:
                decoded = zlib.decompress(payload[4:])
            except zlib.error as error:
                raise ExtractionError(f"{resource.path}: zlib decode failed: {error}") from error
            if len(decoded) != expected_size:
                raise ExtractionError(
                    f"{resource.path}: decoded {len(decoded)} bytes, expected {expected_size}"
                )
            return decoded, "zlib", stored_size
        if compression_flags == QT_RESOURCE_COMPRESSED_ZSTD:
            raise ExtractionError(
                f"{resource.path}: zstd-compressed resources are not supported by this tool"
            )
        raise ExtractionError(f"{resource.path}: invalid compression flags 0x{compression_flags:x}")


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def portable_source_path(path: Path) -> str:
    try:
        return "~/" + path.resolve().relative_to(Path.home().resolve()).as_posix()
    except (OSError, ValueError):
        return str(path)


def safe_output_path(root: Path, resource_path: str) -> Path:
    relative = PurePosixPath(resource_path.lstrip("/"))
    if not relative.parts or any(part in ("", ".", "..") for part in relative.parts):
        raise ExtractionError(f"unsafe resource path: {resource_path!r}")
    return root.joinpath(*relative.parts)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract embedded application QML from the official macOS Tibia client."
    )
    parser.add_argument("--client", type=Path, default=DEFAULT_CLIENT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument(
        "--marker",
        action="append",
        default=[],
        help=(
            "resource basename used to select the application tree; repeatable "
            "(default: clientwindow.qml and gamewindow.qml)"
        ),
    )
    parser.add_argument(
        "--list-trees",
        action="store_true",
        help="print all valid embedded resource trees without extracting",
    )
    parser.add_argument(
        "--no-companions",
        action="store_true",
        help="exclude qmldir/qmltypes trees adjacent to the selected application tree",
    )
    return parser.parse_args()


def load_trees(image: MachOImage) -> list[tuple[Registration, QtResourceTree, list[Resource]]]:
    valid = []
    for registration in image.registrations():
        tree = QtResourceTree(image, registration)
        try:
            resources = tree.resources()
        except (ExtractionError, UnicodeDecodeError, struct.error):
            continue
        if resources:
            valid.append((registration, tree, resources))
    return valid


def main() -> int:
    args = parse_args()
    markers = set(args.marker or ["clientwindow.qml", "gamewindow.qml"])

    try:
        image = MachOImage(args.client)
        trees = load_trees(image)
    except ExtractionError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    if args.list_trees:
        for index, (registration, _tree, resources) in enumerate(trees):
            qml_count = sum(resource.path.endswith(".qml") for resource in resources)
            basenames = {PurePosixPath(resource.path).name for resource in resources}
            matched = sorted(markers & basenames)
            sample = ", ".join(resource.path for resource in resources[:4])
            print(
                f"tree={index} resources={len(resources)} qml={qml_count} "
                f"tree_offset=0x{registration.tree_offset:x} "
                f"markers={matched or '-'} sample={sample}"
            )
        return 0

    selected = []
    for registration, tree, resources in trees:
        basenames = {PurePosixPath(resource.path).name for resource in resources}
        if markers.issubset(basenames):
            selected.append((registration, tree, resources))
    if not selected:
        print(
            f"error: no embedded resource tree contains all markers: {sorted(markers)}",
            file=sys.stderr,
        )
        print("hint: run with --list-trees to inspect discovered trees", file=sys.stderr)
        return 1

    if not args.no_companions:
        selected_registrations = {item[0] for item in selected}
        for registration, tree, resources in trees:
            if registration in selected_registrations:
                continue
            is_qmlcomponents_metadata = all(
                resource.path.startswith("/qt/qml/qmlcomponents/")
                and (
                    PurePosixPath(resource.path).name == "qmldir"
                    or resource.path.endswith(".qmltypes")
                )
                for resource in resources
            )
            if is_qmlcomponents_metadata:
                selected.append((registration, tree, resources))
        selected.sort(key=lambda item: item[0].tree_offset)

    manifest_resources = []
    written_paths: dict[str, str] = {}
    try:
        for tree_index, (registration, tree, resources) in enumerate(selected):
            for resource in resources:
                decoded, compression, stored_size = tree.decoded_payload(resource)
                digest = sha256_bytes(decoded)
                previous_digest = written_paths.get(resource.path)
                if previous_digest is not None:
                    if previous_digest != digest:
                        raise ExtractionError(
                            f"conflicting embedded resources for {resource.path}"
                        )
                    continue
                written_paths[resource.path] = digest
                output_path = safe_output_path(args.output, resource.path)
                output_path.parent.mkdir(parents=True, exist_ok=True)
                output_path.write_bytes(decoded)
                manifest_resources.append(
                    {
                        "resource_path": resource.path,
                        "snapshot_path": output_path.as_posix(),
                        "bytes": len(decoded),
                        "stored_bytes": stored_size,
                        "sha256": digest,
                        "compression": compression,
                        "flags": resource.flags,
                        "territory": resource.territory,
                        "language": resource.language,
                        "modified_msec": resource.modified_msec,
                        "tree_index": tree_index,
                    }
                )
    except (ExtractionError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    manifest_resources.sort(key=lambda item: item["resource_path"])
    manifest = {
        "format": 1,
        "source_executable": portable_source_path(args.client),
        "source_sha256": sha256_bytes(image.data),
        "qt_resource_version": 3,
        "selection_markers": sorted(markers),
        "selected_tree_count": len(selected),
        "resource_count": len(manifest_resources),
        "qml_count": sum(
            item["resource_path"].endswith(".qml") for item in manifest_resources
        ),
        "decoded_bytes": sum(item["bytes"] for item in manifest_resources),
        "registrations": [
            {
                "call_site_offset": registration.call_site_offset,
                "tree_offset": registration.tree_offset,
                "names_offset": registration.names_offset,
                "payloads_offset": registration.payloads_offset,
            }
            for registration, _tree, _resources in selected
        ],
        "resources": manifest_resources,
    }
    try:
        args.manifest.parent.mkdir(parents=True, exist_ok=True)
        args.manifest.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    except OSError as error:
        print(f"error: cannot write manifest {args.manifest}: {error}", file=sys.stderr)
        return 1

    print(
        f"extracted {manifest['resource_count']} resources "
        f"({manifest['qml_count']} QML files, {manifest['decoded_bytes']} decoded bytes) "
        f"to {args.output}"
    )
    print(f"manifest: {args.manifest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
